### PR TITLE
[FEATURE] Modify flutter date picker

### PR DESCRIPTION
**Pull request by quocman-sutrix**

### CODE REVIEW

**Review by purnomoeko — COMMENTED** [review]
Can we have the implmenetation on example folder?

**Comment by purnomoeko** [comment]
Screenshot 2020-12-21 at 3 35 16 PM
On the simulator, can we make it smaller on the example page?

**Comment by quocman-sutrix** [comment]
hi @purnomoeko I added the demo screen.
currently we can set height for calendar to make it smaller. You can see it on example.

**Comment by purnomoeko** [comment]
@quocman-sutrix merged.

**Pull request merged**
